version: '3.3'

services:
   wordpress:
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     volumes:
      - ./checkout:/var/www/html/wp-content/themes/checkout
     environment:
       WORDPRESS_DB_HOST: host.docker.internal:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: Helium 10
       WORDPRESS_DB_NAME: wordpress